export const EXCEL_COLS = [
  "Def. Progetto",
  "Materiale",
  "Descrizione Materiale",
  "Divisione",
  "Descrizione Divisione",
  "Magazzino",
  "Descrizione Magazzino",
  "Qnt. a Mag. bloccato",
  "Controllo Qualità Progetto",
  "Valore per Stock",
  "Controllo Qualità Magazzino",
  "Valore a Magazzino",
  "Bloccato Progetto",
  "Scarico Tot",
  "Qnt. stock prog",
  "Finalità di Utilizzo",
  "Gruppo Merci",
  "Descrizione Gruppo Merci",
  "Profit Center",
  "Descrizione Profit Center",
  "Unità di Misura",
  "Qnt. a Mag. libero",
  "Tipo Valore",
  "Centro Resp.",
  "Descrizione Centro Resp.",
  "Descrizione Contab.",
  "Data Primo utilizzo previsto",
  "Data Ultimo utilizzo previsto",
  "Data Prima EM",
  "Data Ultima EM",
  "Materiale Pianif.",
] as const;

export type ExcelCol = (typeof EXCEL_COLS)[number];

export const DEFAULT_VISIBLE_EXCEL_COLS: ExcelCol[] = [...EXCEL_COLS];
